# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: ac3c7f33fcb45c97e333e413666dcf8d364935e2eb8715e177c06225269f6e2e70b98dd6b7b879850a18320a1e8eaa77f1c2d8a760d88fb57757ef9f0faf5e69

test:
  domain_name: example.com 
  secret_key_base: 8c1f69db9d1895025ad79e9198b22870db6e1cf523524e68afa89304b7e2b6a087f6567f1fa195836910517990d87646a3de9a39677f4cc669f59829683199b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
#production:
#  admin_name: <%= ENV["ADMIN_NAME"] %>
#  admin_email: <%= ENV["ADMIN_EMAIL"] %>
#  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
#  domain_name: <%= ENV["DOMAIN_NAME"] %>
#  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  admin_name: Yosef Yudilevich
  admin_email: yosefy@gmail.com
  admin_password: galaxy123
  domain_name: galaxy.kbb1.com
  secret_key_base: 8c1f69db9d1895025ad79e9198b22870db6e1cf523524e68afa89304b7e2b6a087f6567f1fa195836910517990d87646a3de9a39677f4cc669f59829683199b2
